# Generated by Django 2.0.6 on 2018-12-05 17:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('attendanceApp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='attendancemodel',
            old_name='firstName',
            new_name='password',
        ),
        migrations.RemoveField(
            model_name='attendancemodel',
            name='lastName',
        ),
    ]
