# Generated by Django 2.0.6 on 2018-12-05 21:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendanceApp', '0003_auto_20181205_2118'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attendancemodel',
            name='clockIn',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='attendancemodel',
            name='clockOut',
            field=models.DateTimeField(null=True),
        ),
    ]
