# Generated by Django 2.0.6 on 2018-12-06 17:14

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendanceApp', '0007_auto_20181206_1708'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clockin',
            name='clockIn',
            field=models.DateTimeField(default=datetime.datetime(2018, 12, 6, 17, 14, 41, 359131)),
        ),
        migrations.AlterField(
            model_name='clockout',
            name='clockOut',
            field=models.DateTimeField(default=datetime.datetime(2018, 12, 6, 17, 14, 41, 359572)),
        ),
    ]
