# Generated by Django 2.0.6 on 2018-12-06 21:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('attendanceApp', '0008_auto_20181206_1714'),
        ('attendanceApp', '0003_auto_20181205_2123'),
    ]

    operations = [
    ]
